In [1]:
import numpy as np
import bs4 as soup
import requests

In [3]:
X = np.array([
    [1,2,3],
    [4,5,6]
])

In [4]:
X

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
y = np.array([10,20,30])

In [6]:
y

array([10, 20, 30])

In [7]:
X + y

array([[11, 22, 33],
       [14, 25, 36]])